export interface Iuserprofile {
    id: number,
    businessName: string,
    gstin: string,
    tdsGstin: string,
    address: string,
    email: string,
    contactNumber: string,
    turnOver: string,
    bankAccountNumber: string,
    ifscCode: string,
    registrationType: string,
    termsAndCondition: string,
    imgUrl: string,
    placeOfSupply:number,
    selectedYear : Date,
    bankAccountName : string,
    currentGrossTurnOver : number,
    pan: string,
    
}
